# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rig1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1480, 915)
        MainWindow.setAnimated(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-50, 0, 1331, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 10, 441, 51))
        self.label.setStyleSheet(_fromUtf8("font: 75 22pt \"Segoe Script\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(560, 0, 231, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_14.setStyleSheet(_fromUtf8("color : blue;\n"
"font: 14pt \"Poor Richard\";\n"
""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_3.addWidget(self.label_14)
        self.BaudCombo = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.BaudCombo.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.BaudCombo.setObjectName(_fromUtf8("BaudCombo"))
        self.BaudCombo.addItem(_fromUtf8(""))
        self.BaudCombo.addItem(_fromUtf8(""))
        self.BaudCombo.addItem(_fromUtf8(""))
        self.BaudCombo.addItem(_fromUtf8(""))
        self.BaudCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.BaudCombo)
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_3.addWidget(self.label_12)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(560, 40, 231, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";color : blue;\n"
""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.BytesizeCombo = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.BytesizeCombo.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.BytesizeCombo.setObjectName(_fromUtf8("BytesizeCombo"))
        self.BytesizeCombo.addItem(_fromUtf8(""))
        self.BytesizeCombo.addItem(_fromUtf8(""))
        self.BytesizeCombo.addItem(_fromUtf8(""))
        self.BytesizeCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.BytesizeCombo)
        self.label_18 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_18.setText(_fromUtf8(""))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_5.addWidget(self.label_18)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(790, 0, 181, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_6.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
"color : blue;"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.ParityCombo = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.ParityCombo.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.ParityCombo.setObjectName(_fromUtf8("ParityCombo"))
        self.ParityCombo.addItem(_fromUtf8(""))
        self.ParityCombo.addItem(_fromUtf8(""))
        self.ParityCombo.addItem(_fromUtf8(""))
        self.ParityCombo.addItem(_fromUtf8(""))
        self.ParityCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.ParityCombo)
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_6.addWidget(self.label_19)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(790, 40, 181, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_13.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";color : blue;\n"
""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_7.addWidget(self.label_13)
        self.StopbitsCombo = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        self.StopbitsCombo.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.StopbitsCombo.setObjectName(_fromUtf8("StopbitsCombo"))
        self.StopbitsCombo.addItem(_fromUtf8(""))
        self.StopbitsCombo.addItem(_fromUtf8(""))
        self.StopbitsCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.StopbitsCombo)
        self.label_20 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_7.addWidget(self.label_20)
        self.DisconnectBut = QtGui.QPushButton(self.frame)
        self.DisconnectBut.setEnabled(True)
        self.DisconnectBut.setGeometry(QtCore.QRect(1000, 10, 161, 51))
        self.DisconnectBut.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.DisconnectBut.setObjectName(_fromUtf8("DisconnectBut"))
        self.ConnectBut = QtGui.QPushButton(self.frame)
        self.ConnectBut.setGeometry(QtCore.QRect(1000, 10, 161, 51))
        self.ConnectBut.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.ConnectBut.setObjectName(_fromUtf8("ConnectBut"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 60, 1121, 581))
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 701, 441))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_4 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 7, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.PulseB = QtGui.QCheckBox(self.gridLayoutWidget)
        self.PulseB.setObjectName(_fromUtf8("PulseB"))
        self.gridLayout.addWidget(self.PulseB, 16, 0, 1, 1)
        self.SynEvents = QtGui.QCheckBox(self.gridLayoutWidget)
        self.SynEvents.setObjectName(_fromUtf8("SynEvents"))
        self.gridLayout.addWidget(self.SynEvents, 17, 0, 1, 1)
        self.TransMessage = QtGui.QCheckBox(self.gridLayoutWidget)
        self.TransMessage.setObjectName(_fromUtf8("TransMessage"))
        self.gridLayout.addWidget(self.TransMessage, 19, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 6, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 6, 2, 1, 1)
        self.VarFreq = QtGui.QCheckBox(self.gridLayoutWidget)
        self.VarFreq.setObjectName(_fromUtf8("VarFreq"))
        self.gridLayout.addWidget(self.VarFreq, 15, 0, 1, 1)
        self.AsynEvents = QtGui.QCheckBox(self.gridLayoutWidget)
        self.AsynEvents.setObjectName(_fromUtf8("AsynEvents"))
        self.gridLayout.addWidget(self.AsynEvents, 18, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_15.setStyleSheet(_fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 14, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 3)
        self.ClockVar = QtGui.QCheckBox(self.gridLayoutWidget)
        self.ClockVar.setObjectName(_fromUtf8("ClockVar"))
        self.gridLayout.addWidget(self.ClockVar, 12, 0, 1, 1)
        self.MessageCheck = QtGui.QCheckBox(self.gridLayoutWidget)
        self.MessageCheck.setObjectName(_fromUtf8("MessageCheck"))
        self.gridLayout.addWidget(self.MessageCheck, 9, 0, 1, 1)
        self.mirrorMessageRx = QtGui.QCheckBox(self.gridLayoutWidget)
        self.mirrorMessageRx.setObjectName(_fromUtf8("mirrorMessageRx"))
        self.gridLayout.addWidget(self.mirrorMessageRx, 7, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout.addWidget(self.lineEdit_9, 7, 3, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout.addWidget(self.lineEdit_8, 7, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 6, 3, 1, 1)
        self.mirrorMessage = QtGui.QCheckBox(self.gridLayoutWidget)
        self.mirrorMessage.setObjectName(_fromUtf8("mirrorMessage"))
        self.gridLayout.addWidget(self.mirrorMessage, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 10, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 11, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_34.setStyleSheet(_fromUtf8("font: 75 11pt \"MS Shell Dlg 2\";"))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 3, 2, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setEnabled(False)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout.addWidget(self.radioButton, 3, 1, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout.addWidget(self.radioButton_2, 4, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 13, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(720, 0, 20, 551))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_35 = QtGui.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(780, 20, 211, 16))
        self.label_35.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.QueueAdd = QtGui.QPushButton(self.tab)
        self.QueueAdd.setGeometry(QtCore.QRect(370, 490, 151, 41))
        self.QueueAdd.setStyleSheet(_fromUtf8("\n"
"font: 75 16pt \"MS Shell Dlg 2\";"))
        self.QueueAdd.setObjectName(_fromUtf8("QueueAdd"))
        self.label_36 = QtGui.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(10, 480, 101, 51))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(0, 460, 731, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.testid = QtGui.QLabel(self.tab)
        self.testid.setGeometry(QtCore.QRect(130, 490, 111, 31))
        self.testid.setText(_fromUtf8(""))
        self.testid.setObjectName(_fromUtf8("testid"))
        self.queueList = QtGui.QLabel(self.tab)
        self.queueList.setGeometry(QtCore.QRect(750, 50, 331, 491))
        self.queueList.setStyleSheet(_fromUtf8("font: 75 18pt \"System\";\n"
"background-color: rgb(255, 255, 255);"))
        self.queueList.setText(_fromUtf8(""))
        self.queueList.setObjectName(_fromUtf8("queueList"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1480, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(200, 650))
        self.dockWidget.setMaximumSize(QtCore.QSize(200, 650))
        self.dockWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidget.setStyleSheet(_fromUtf8(""))
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 201, 601))
        self.groupBox.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 181, 571))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.statusBut = QtGui.QPushButton(self.verticalLayoutWidget)
        self.statusBut.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.statusBut.setObjectName(_fromUtf8("statusBut"))
        self.verticalLayout.addWidget(self.statusBut)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBox_5 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.horizontalLayout.addWidget(self.checkBox_5)
        self.comboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem5 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.EmergencyBut = QtGui.QPushButton(self.verticalLayoutWidget)
        self.EmergencyBut.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.EmergencyBut.setObjectName(_fromUtf8("EmergencyBut"))
        self.verticalLayout.addWidget(self.EmergencyBut)
        self.resetEBut = QtGui.QPushButton(self.verticalLayoutWidget)
        self.resetEBut.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.resetEBut.setObjectName(_fromUtf8("resetEBut"))
        self.verticalLayout.addWidget(self.resetEBut)
        self.OFBut = QtGui.QPushButton(self.verticalLayoutWidget)
        self.OFBut.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.OFBut.setObjectName(_fromUtf8("OFBut"))
        self.verticalLayout.addWidget(self.OFBut)
        self.OFDBut = QtGui.QPushButton(self.verticalLayoutWidget)
        self.OFDBut.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.OFDBut.setObjectName(_fromUtf8("OFDBut"))
        self.verticalLayout.addWidget(self.OFDBut)
        self.OCUBut = QtGui.QPushButton(self.verticalLayoutWidget)
        self.OCUBut.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.OCUBut.setObjectName(_fromUtf8("OCUBut"))
        self.verticalLayout.addWidget(self.OCUBut)
        self.OCDBut = QtGui.QPushButton(self.verticalLayoutWidget)
        self.OCDBut.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.OCDBut.setObjectName(_fromUtf8("OCDBut"))
        self.verticalLayout.addWidget(self.OCDBut)
        spacerItem6 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem6)
        self.Transponder = QtGui.QPushButton(self.verticalLayoutWidget)
        self.Transponder.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.Transponder.setObjectName(_fromUtf8("Transponder"))
        self.verticalLayout.addWidget(self.Transponder)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBox_11 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.horizontalLayout_2.addWidget(self.checkBox_11)
        self.comboBox_3 = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_3)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem7)
        self.airspeed = QtGui.QPushButton(self.verticalLayoutWidget)
        self.airspeed.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.airspeed.setObjectName(_fromUtf8("airspeed"))
        self.verticalLayout.addWidget(self.airspeed)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBox_13 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.horizontalLayout_4.addWidget(self.checkBox_13)
        self.comboBox_2 = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_4.addWidget(self.label_17)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.pushButton_2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.pushButton_2)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_3 = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_3.sizePolicy().hasHeightForWidth())
        self.dockWidget_3.setSizePolicy(sizePolicy)
        self.dockWidget_3.setMinimumSize(QtCore.QSize(1480, 220))
        self.dockWidget_3.setMaximumSize(QtCore.QSize(1480, 220))
        self.dockWidget_3.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_3.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockWidget_3.setObjectName(_fromUtf8("dockWidget_3"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 791, 191))
        self.groupBox_2.setSizeIncrement(QtCore.QSize(2, 2))
        self.groupBox_2.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.rawoutput = QtGui.QPlainTextEdit(self.groupBox_2)
        self.rawoutput.setGeometry(QtCore.QRect(10, 70, 641, 111))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawoutput.sizePolicy().hasHeightForWidth())
        self.rawoutput.setSizePolicy(sizePolicy)
        self.rawoutput.setReadOnly(True)
        self.rawoutput.setCenterOnScroll(False)
        self.rawoutput.setObjectName(_fromUtf8("rawoutput"))
        self.terminal = QtGui.QLineEdit(self.groupBox_2)
        self.terminal.setGeometry(QtCore.QRect(10, 30, 641, 20))
        self.terminal.setObjectName(_fromUtf8("terminal"))
        self.TerminalSend = QtGui.QPushButton(self.groupBox_2)
        self.TerminalSend.setGeometry(QtCore.QRect(680, 22, 101, 31))
        self.TerminalSend.setObjectName(_fromUtf8("TerminalSend"))
        self.getOutputBut = QtGui.QPushButton(self.groupBox_2)
        self.getOutputBut.setGeometry(QtCore.QRect(680, 72, 101, 31))
        self.getOutputBut.setObjectName(_fromUtf8("getOutputBut"))
        self.terminalClearBut = QtGui.QPushButton(self.groupBox_2)
        self.terminalClearBut.setGeometry(QtCore.QRect(680, 110, 101, 41))
        self.terminalClearBut.setObjectName(_fromUtf8("terminalClearBut"))
        self.groupBox_3 = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_3.setGeometry(QtCore.QRect(800, 10, 661, 191))
        self.groupBox_3.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";"))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 647, 161))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_25.setStyleSheet(_fromUtf8(""))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_24.setStyleSheet(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 1, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 2, 10, 1, 1)
        self.label_32 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 1, 10, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_31.setStyleSheet(_fromUtf8(""))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 1, 8, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_28.setStyleSheet(_fromUtf8(""))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 2, 8, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_23.setStyleSheet(_fromUtf8(""))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 2, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setStyleSheet(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lcdNumber_4 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.gridLayout_2.addWidget(self.lcdNumber_4, 2, 5, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_22.setStyleSheet(_fromUtf8(""))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 1, 4, 1, 1)
        self.lcdNumber_5 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.gridLayout_2.addWidget(self.lcdNumber_5, 1, 9, 1, 1)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.gridLayout_2.addWidget(self.lcdNumber_3, 1, 5, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 2, 6, 1, 1)
        self.lcdNumber_6 = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.gridLayout_2.addWidget(self.lcdNumber_6, 2, 9, 1, 1)
        self.lcdstcpuvoltage = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdstcpuvoltage.setObjectName(_fromUtf8("lcdstcpuvoltage"))
        self.gridLayout_2.addWidget(self.lcdstcpuvoltage, 2, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 1, 6, 1, 1)
        self.label_30 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 0, 8, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_21.setStyleSheet(_fromUtf8(""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.lcdstcputemp = QtGui.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdstcputemp.setObjectName(_fromUtf8("lcdstcputemp"))
        self.gridLayout_2.addWidget(self.lcdstcputemp, 1, 1, 1, 1)
        self.line = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 0, 7, 3, 1)
        self.line_2 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 1, 3, 2, 1)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_3)
        self.dockWidget_4 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_4.setMinimumSize(QtCore.QSize(150, 650))
        self.dockWidget_4.setMaximumSize(QtCore.QSize(150, 650))
        self.dockWidget_4.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_4.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_4.setObjectName(_fromUtf8("dockWidget_4"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.dockWidgetContents_4)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 0, 211, 361))
        self.groupBox_5.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 211, 331))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem9)
        self.batlow = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.batlow.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
""))
        self.batlow.setObjectName(_fromUtf8("batlow"))
        self.verticalLayout_2.addWidget(self.batlow)
        self.vib42 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.vib42.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
"background-color: rgb(255, 255, 255);"))
        self.vib42.setObjectName(_fromUtf8("vib42"))
        self.verticalLayout_2.addWidget(self.vib42)
        self.thrust = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.thrust.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
"background-color: rgb(255, 255, 255);"))
        self.thrust.setObjectName(_fromUtf8("thrust"))
        self.verticalLayout_2.addWidget(self.thrust)
        self.deicing = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.deicing.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";\n"
"background-color: rgb(255, 255, 255);"))
        self.deicing.setObjectName(_fromUtf8("deicing"))
        self.verticalLayout_2.addWidget(self.deicing)
        self.comp54 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.comp54.setStyleSheet(_fromUtf8("font: 14pt \"Poor Richard\";background-color: rgb(255, 255, 255);"))
        self.comp54.setObjectName(_fromUtf8("comp54"))
        self.verticalLayout_2.addWidget(self.comp54)
        self.dockWidget_4.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_4)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.mirrorMessage, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.radioButton.setEnabled)
        QtCore.QObject.connect(self.mirrorMessage, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit.setEnabled)
        QtCore.QObject.connect(self.mirrorMessage, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.radioButton_2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Embedded System Test Rig", None))
        self.label_14.setText(_translate("MainWindow", "Baudrate", None))
        self.BaudCombo.setItemText(0, _translate("MainWindow", "9600", None))
        self.BaudCombo.setItemText(1, _translate("MainWindow", "19200", None))
        self.BaudCombo.setItemText(2, _translate("MainWindow", "38400", None))
        self.BaudCombo.setItemText(3, _translate("MainWindow", "57600", None))
        self.BaudCombo.setItemText(4, _translate("MainWindow", "115200", None))
        self.label_3.setText(_translate("MainWindow", "Bytesize", None))
        self.BytesizeCombo.setItemText(0, _translate("MainWindow", "Eight Bits", None))
        self.BytesizeCombo.setItemText(1, _translate("MainWindow", "Seven Bits", None))
        self.BytesizeCombo.setItemText(2, _translate("MainWindow", "Six Bits", None))
        self.BytesizeCombo.setItemText(3, _translate("MainWindow", "Five Bits", None))
        self.label_6.setText(_translate("MainWindow", "Parity", None))
        self.ParityCombo.setItemText(0, _translate("MainWindow", "Even", None))
        self.ParityCombo.setItemText(1, _translate("MainWindow", "None", None))
        self.ParityCombo.setItemText(2, _translate("MainWindow", "Odd", None))
        self.ParityCombo.setItemText(3, _translate("MainWindow", "Mark", None))
        self.ParityCombo.setItemText(4, _translate("MainWindow", "Space", None))
        self.label_13.setText(_translate("MainWindow", "Stopbits", None))
        self.StopbitsCombo.setItemText(0, _translate("MainWindow", "1", None))
        self.StopbitsCombo.setItemText(1, _translate("MainWindow", "1.5", None))
        self.StopbitsCombo.setItemText(2, _translate("MainWindow", "2", None))
        self.DisconnectBut.setText(_translate("MainWindow", "Disconnect", None))
        self.ConnectBut.setText(_translate("MainWindow", "Connect", None))
        self.PulseB.setText(_translate("MainWindow", "Pulse Burst", None))
        self.SynEvents.setText(_translate("MainWindow", "Synchronous Events", None))
        self.TransMessage.setText(_translate("MainWindow", "Transponder Message reception check", None))
        self.label_7.setText(_translate("MainWindow", "TextLabel", None))
        self.label_5.setText(_translate("MainWindow", "Parameters", None))
        self.label_8.setText(_translate("MainWindow", "TextLabel", None))
        self.VarFreq.setText(_translate("MainWindow", "Variable Frequency", None))
        self.AsynEvents.setText(_translate("MainWindow", "Asynchronous Events", None))
        self.label_15.setText(_translate("MainWindow", "Pin-change Interrupt Tests", None))
        self.label_2.setText(_translate("MainWindow", "Text to be Mirror", None))
        self.ClockVar.setText(_translate("MainWindow", "UUT Clock Variation", None))
        self.MessageCheck.setText(_translate("MainWindow", "Message Check", None))
        self.mirrorMessageRx.setText(_translate("MainWindow", "Mirror message RX to ESTR:", None))
        self.label_9.setText(_translate("MainWindow", "TextLabel", None))
        self.mirrorMessage.setText(_translate("MainWindow", "Mirror Message TX to UUT:", None))
        self.label_16.setText(_translate("MainWindow", "TextLabel", None))
        self.label_34.setText(_translate("MainWindow", "UART Tests", None))
        self.radioButton.setText(_translate("MainWindow", "Message", None))
        self.radioButton_2.setText(_translate("MainWindow", "Random Generated Message", None))
        self.label_35.setText(_translate("MainWindow", "Results", None))
        self.QueueAdd.setText(_translate("MainWindow", "Add to Queue", None))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">TEST ID:</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Test\\s Parameters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Test\\s Results", None))
        self.groupBox.setTitle(_translate("MainWindow", "Commands", None))
        self.statusBut.setText(_translate("MainWindow", "Send Status", None))
        self.checkBox_5.setText(_translate("MainWindow", "Every", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "10", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "20", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "50", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "100", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "250", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "500", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "1000", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "2000", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "3000", None))
        self.label_10.setText(_translate("MainWindow", "ms", None))
        self.EmergencyBut.setText(_translate("MainWindow", "Emergency", None))
        self.resetEBut.setText(_translate("MainWindow", "Reset Emergency", None))
        self.OFBut.setText(_translate("MainWindow", "Osc Fine Up", None))
        self.OFDBut.setText(_translate("MainWindow", "Osc Fine Down", None))
        self.OCUBut.setText(_translate("MainWindow", "Osc Coarse Up", None))
        self.OCDBut.setText(_translate("MainWindow", "Osc Coarse Down", None))
        self.Transponder.setText(_translate("MainWindow", "Transponder", None))
        self.checkBox_11.setText(_translate("MainWindow", "Every", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "10", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "20", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "50", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "100", None))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "250", None))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "500", None))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "1000", None))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "2000", None))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "3000", None))
        self.label_11.setText(_translate("MainWindow", "ms", None))
        self.airspeed.setText(_translate("MainWindow", "Air Speed", None))
        self.checkBox_13.setText(_translate("MainWindow", "Every", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "10", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "20", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "50", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "100", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "250", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "500", None))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "1000", None))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "2000", None))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "3000", None))
        self.label_17.setText(_translate("MainWindow", "ms", None))
        self.pushButton_2.setText(_translate("MainWindow", "Reset", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Terminal", None))
        self.TerminalSend.setText(_translate("MainWindow", "Send", None))
        self.getOutputBut.setText(_translate("MainWindow", "Get Output", None))
        self.terminalClearBut.setText(_translate("MainWindow", "Clear", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Rocket Information", None))
        self.label_25.setText(_translate("MainWindow", "Volts", None))
        self.label_24.setText(_translate("MainWindow", "\'C", None))
        self.label_33.setText(_translate("MainWindow", "Feet", None))
        self.label_32.setText(_translate("MainWindow", "Units", None))
        self.label_31.setText(_translate("MainWindow", "Air Speed", None))
        self.label_29.setText(_translate("MainWindow", "ST", None))
        self.label_28.setText(_translate("MainWindow", "Altitude", None))
        self.label_23.setText(_translate("MainWindow", "Altitude", None))
        self.label_4.setText(_translate("MainWindow", "CPU Temp", None))
        self.label_22.setText(_translate("MainWindow", "Air Speed", None))
        self.label_27.setText(_translate("MainWindow", "Feet", None))
        self.label_26.setText(_translate("MainWindow", "Units", None))
        self.label_30.setText(_translate("MainWindow", "TP", None))
        self.label_21.setText(_translate("MainWindow", "CPU Voltage", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Error Codes", None))
        self.batlow.setText(_translate("MainWindow", "<html><head/><body><p>Battery power </p><p>critically low</p></body></html>", None))
        self.vib42.setText(_translate("MainWindow", "<html><head/><body><p>Vibrations </p><p>exceeding </p><p>42%</p></body></html>", None))
        self.thrust.setText(_translate("MainWindow", "<html><head/><body><p>Thrust loss</p></body></html>", None))
        self.deicing.setText(_translate("MainWindow", "<html><head/><body><p>Deicing failure</p></body></html>", None))
        self.comp54.setText(_translate("MainWindow", "<html><head/><body><p>Computing error </p><p>54</p></body></html>", None))

#import hold_rc
